rates = "ONLIB.X,1WLIB.X,1MLIB.X,2MLIB.X,3MLIB.X,4MLIB.X,5MLIB.X," + \
  "6MLIB.X,7MLIB.X,8MLIB.X,9MLIB.X,10MLIB.X,11MLIB.X,1YLIB.X"

stocks = "ABX"#,CAT,BA,GE,MMM,F,NKE,KO,PEP,PG,XOM,BAC,C,JNJ,PFE," + \
#  "GOOG,GOOGL,T,WMT,AAPL,MSFT,FDX,BP,IBM,AMZN,OEX.XO,SPX.XO,VIX.XO," + \
#  "TSLA,FB,WFM,YHOO,TWTR,VZ,MCD,DAL,CSCO,AMD,AAL,VXX," + \
#  "CVS,MO,CMCSA,DIS,NVDA,MRK,V,ACN,LMT,GD,RTN,NOC,ORCL,INTC,NFLX,CMG"


rates = rates.split(',')
stocks = stocks.split(',')

